services:

  mysql:
    image: mariadb:latest
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8084:80
    environment:
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_HOST: mysql
      UPLOAD_LIMIT: 64M

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./.env
    ports:
      - 8083:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DEBUG: true
    volumes:
      - ./wp-content/languages:/var/www/html/wp-content/languages
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/uploads:/var/www/html/wp-content/uploads

volumes:
  mysql-data:
